package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "\u8EAB\u4EFD\u4FE1\u606F")
	private com.myteam.loanproduct.Identity identity;
	@org.kie.api.definition.type.Label(value = "\u5DE5\u4F5C\u4FE1\u606F")
	private com.myteam.loanproduct.Employment employment;
	@org.kie.api.definition.type.Label(value = "\u8F66")
	private com.myteam.loanproduct.Car car;
	@org.kie.api.definition.type.Label(value = "\u623F")
	private com.myteam.loanproduct.House house;
	@org.kie.api.definition.type.Label(value = "\u5BFF\u9669")
	private com.myteam.loanproduct.LifeInsurance lifeInsurance;
	@org.kie.api.definition.type.Label(value = "\u4FE1\u7528")
	private com.myteam.loanproduct.Credit credit;
	@org.kie.api.definition.type.Label(value = "\u8D1F\u503A")
	private com.myteam.loanproduct.Debt debt;

	public Applicant() {
	}

	public com.myteam.loanproduct.Identity getIdentity() {
		return this.identity;
	}

	public void setIdentity(com.myteam.loanproduct.Identity identity) {
		this.identity = identity;
	}

	public com.myteam.loanproduct.Employment getEmployment() {
		return this.employment;
	}

	public void setEmployment(com.myteam.loanproduct.Employment employment) {
		this.employment = employment;
	}

	public com.myteam.loanproduct.Car getCar() {
		return this.car;
	}

	public void setCar(com.myteam.loanproduct.Car car) {
		this.car = car;
	}

	public com.myteam.loanproduct.House getHouse() {
		return this.house;
	}

	public void setHouse(com.myteam.loanproduct.House house) {
		this.house = house;
	}

	public com.myteam.loanproduct.LifeInsurance getLifeInsurance() {
		return this.lifeInsurance;
	}

	public void setLifeInsurance(
			com.myteam.loanproduct.LifeInsurance lifeInsurance) {
		this.lifeInsurance = lifeInsurance;
	}

	public com.myteam.loanproduct.Credit getCredit() {
		return this.credit;
	}

	public void setCredit(com.myteam.loanproduct.Credit credit) {
		this.credit = credit;
	}

	public com.myteam.loanproduct.Debt getDebt() {
		return this.debt;
	}

	public void setDebt(com.myteam.loanproduct.Debt debt) {
		this.debt = debt;
	}

	public Applicant(com.myteam.loanproduct.Identity identity,
			com.myteam.loanproduct.Employment employment,
			com.myteam.loanproduct.Car car, com.myteam.loanproduct.House house,
			com.myteam.loanproduct.LifeInsurance lifeInsurance,
			com.myteam.loanproduct.Credit credit,
			com.myteam.loanproduct.Debt debt) {
		this.identity = identity;
		this.employment = employment;
		this.car = car;
		this.house = house;
		this.lifeInsurance = lifeInsurance;
		this.credit = credit;
		this.debt = debt;
	}

}