package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Car implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "\u6309\u63ED\u8D37\u6B3E")
	private com.myteam.loanproduct.Repayment loanRepayment;
	@org.kie.api.definition.type.Label(value = "\u8F66\u9F84")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "\u662F\u5426\u4E8C\u624B")
	private java.lang.Boolean isSecondHand;
	@org.kie.api.definition.type.Label(value = "\u8D2D\u4E70\u4FE1\u606F")
	private com.myteam.loanproduct.Order order;
	@org.kie.api.definition.type.Label(value = "\u662F\u5426\u88AB\u62B5\u62BC")
	private java.lang.Boolean isCollateral;
	@org.kie.api.definition.type.Label(value = "\u8BC4\u4F30\u4EF7")
	private java.lang.Integer evaluatedPrice;

	public Car() {
	}

	public com.myteam.loanproduct.Repayment getLoanRepayment() {
		return this.loanRepayment;
	}

	public void setLoanRepayment(com.myteam.loanproduct.Repayment loanRepayment) {
		this.loanRepayment = loanRepayment;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Boolean getIsSecondHand() {
		return this.isSecondHand;
	}

	public void setIsSecondHand(java.lang.Boolean isSecondHand) {
		this.isSecondHand = isSecondHand;
	}

	public com.myteam.loanproduct.Order getOrder() {
		return this.order;
	}

	public void setOrder(com.myteam.loanproduct.Order order) {
		this.order = order;
	}

	public java.lang.Boolean getIsCollateral() {
		return this.isCollateral;
	}

	public void setIsCollateral(java.lang.Boolean isCollateral) {
		this.isCollateral = isCollateral;
	}

	public java.lang.Integer getEvaluatedPrice() {
		return this.evaluatedPrice;
	}

	public void setEvaluatedPrice(java.lang.Integer evaluatedPrice) {
		this.evaluatedPrice = evaluatedPrice;
	}

	public Car(com.myteam.loanproduct.Repayment loanRepayment,
			java.lang.Integer age, java.lang.Boolean isSecondHand,
			com.myteam.loanproduct.Order order, java.lang.Boolean isCollateral,
			java.lang.Integer evaluatedPrice) {
		this.loanRepayment = loanRepayment;
		this.age = age;
		this.isSecondHand = isSecondHand;
		this.order = order;
		this.isCollateral = isCollateral;
		this.evaluatedPrice = evaluatedPrice;
	}

}