package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Company implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("公司类型")
	private Integer type;
	@org.kie.api.definition.type.Label("行业")
	private Industry industry;
	@org.kie.api.definition.type.Label("法定代表人")
	private java.lang.String legalRepresentative;
	@org.kie.api.definition.type.Label("销售额")
	private com.myteam.loanproduct.Sales sales;

	@org.kie.api.definition.type.Label("银行流水")
	private com.myteam.loanproduct.BankStatement bankStatement;

	@org.kie.api.definition.type.Label("公司名称")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("简称")
	private java.lang.String abbr;

	@org.kie.api.definition.type.Label("注册时间")
	private java.lang.Integer registrationDateId;

	@org.kie.api.definition.type.Label("有无固定营业场所")
	private java.lang.Boolean fixedBusinessPlace;

	@org.kie.api.definition.type.Label("注册地")
	private com.myteam.loanproduct.District registrationDistrict;

	@org.kie.api.definition.type.Label(value = "ID")
	private java.lang.Integer id;

	public Company() {
	}

	public java.lang.String getLegalRepresentative() {
		return this.legalRepresentative;
	}

	public void setLegalRepresentative(java.lang.String legalRepresentative) {
		this.legalRepresentative = legalRepresentative;
	}

	public com.myteam.loanproduct.Sales getSales() {
		return this.sales;
	}

	public void setSales(com.myteam.loanproduct.Sales sales) {
		this.sales = sales;
	}

	public com.myteam.loanproduct.BankStatement getBankStatement() {
		return this.bankStatement;
	}

	public void setBankStatement(
			com.myteam.loanproduct.BankStatement bankStatement) {
		this.bankStatement = bankStatement;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAbbr() {
		return this.abbr;
	}

	public void setAbbr(java.lang.String abbr) {
		this.abbr = abbr;
	}

	public java.lang.Integer getRegistrationDateId() {
		return this.registrationDateId;
	}

	public void setRegistrationDateId(java.lang.Integer registrationDateId) {
		this.registrationDateId = registrationDateId;
	}

	public java.lang.Boolean getFixedBusinessPlace() {
		return this.fixedBusinessPlace;
	}

	public void setFixedBusinessPlace(java.lang.Boolean fixedBusinessPlace) {
		this.fixedBusinessPlace = fixedBusinessPlace;
	}

	public com.myteam.loanproduct.District getRegistrationDistrict() {
		return this.registrationDistrict;
	}

	public void setRegistrationDistrict(
			com.myteam.loanproduct.District registrationDistrict) {
		this.registrationDistrict = registrationDistrict;
	}

	public java.lang.Integer getType() {
		return this.type;
	}

	public void setType(java.lang.Integer type) {
		this.type = type;
	}

	public com.myteam.loanproduct.Industry getIndustry() {
		return this.industry;
	}

	public void setIndustry(com.myteam.loanproduct.Industry industry) {
		this.industry = industry;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public Company(java.lang.Integer type,
			com.myteam.loanproduct.Industry industry,
			java.lang.String legalRepresentative,
			com.myteam.loanproduct.Sales sales,
			com.myteam.loanproduct.BankStatement bankStatement,
			java.lang.String name, java.lang.String abbr,
			java.lang.Integer registrationDateId,
			java.lang.Boolean fixedBusinessPlace,
			com.myteam.loanproduct.District registrationDistrict,
			java.lang.Integer id) {
		this.type = type;
		this.industry = industry;
		this.legalRepresentative = legalRepresentative;
		this.sales = sales;
		this.bankStatement = bankStatement;
		this.name = name;
		this.abbr = abbr;
		this.registrationDateId = registrationDateId;
		this.fixedBusinessPlace = fixedBusinessPlace;
		this.registrationDistrict = registrationDistrict;
		this.id = id;
	}

}