package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Credit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("是否白户")
	private java.lang.Boolean isBlank;
	@org.kie.api.definition.type.Label("征信报告查询情况")
	private com.myteam.loanproduct.CreditReportInquiries inquiries;
	@org.kie.api.definition.type.Label("逾期情况")
	private com.myteam.loanproduct.LatePayments latePayments;
	@org.kie.api.definition.type.Label(value = "\u8D37\u6B3E\u4F59\u989D")
	private java.lang.Integer debt;

	@org.kie.api.definition.type.Label(value = "\u5F53\u524D\u903E\u671F\u91D1\u989D")
	private java.lang.Integer overdue;

	public Credit() {
	}

	public java.lang.Boolean getIsBlank() {
		return this.isBlank;
	}

	public void setIsBlank(java.lang.Boolean isBlank) {
		this.isBlank = isBlank;
	}

	public com.myteam.loanproduct.CreditReportInquiries getInquiries() {
		return this.inquiries;
	}

	public void setInquiries(
			com.myteam.loanproduct.CreditReportInquiries inquiries) {
		this.inquiries = inquiries;
	}

	public com.myteam.loanproduct.LatePayments getLatePayments() {
		return this.latePayments;
	}

	public void setLatePayments(com.myteam.loanproduct.LatePayments latePayments) {
		this.latePayments = latePayments;
	}

	public java.lang.Integer getDebt() {
		return this.debt;
	}

	public void setDebt(java.lang.Integer debt) {
		this.debt = debt;
	}

	public java.lang.Integer getOverdue() {
		return this.overdue;
	}

	public void setOverdue(java.lang.Integer overdue) {
		this.overdue = overdue;
	}

	public Credit(java.lang.Boolean isBlank,
			com.myteam.loanproduct.CreditReportInquiries inquiries,
			com.myteam.loanproduct.LatePayments latePayments,
			java.lang.Integer debt, java.lang.Integer overdue) {
		this.isBlank = isBlank;
		this.inquiries = inquiries;
		this.latePayments = latePayments;
		this.debt = debt;
		this.overdue = overdue;
	}

}