package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("工作状态")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("公司")
	private com.myteam.loanproduct.Company company;
	@org.kie.api.definition.type.Label("职位")
	private java.lang.String position;
	@org.kie.api.definition.type.Label("月薪")
	private java.lang.Integer monthlySalary;
	@org.kie.api.definition.type.Label("发薪方式")
	private String paidMethod;
	@org.kie.api.definition.type.Label("入职时间（月数）")
	private java.lang.Integer duration;
	@org.kie.api.definition.type.Label("占股")
	private com.myteam.loanproduct.Shares shares;
	@org.kie.api.definition.type.Label("社保")
	private com.myteam.loanproduct.SocialInsurance socialInsurance;
	@org.kie.api.definition.type.Label("住房公积金")
	private com.myteam.loanproduct.HousingFund housingFund;

	public Employment() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public com.myteam.loanproduct.Company getCompany() {
		return this.company;
	}

	public void setCompany(com.myteam.loanproduct.Company company) {
		this.company = company;
	}

	public java.lang.String getPosition() {
		return this.position;
	}

	public void setPosition(java.lang.String position) {
		this.position = position;
	}

	public java.lang.Integer getMonthlySalary() {
		return this.monthlySalary;
	}

	public void setMonthlySalary(java.lang.Integer monthlySalary) {
		this.monthlySalary = monthlySalary;
	}

	public java.lang.Integer getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.Integer duration) {
		this.duration = duration;
	}

	public com.myteam.loanproduct.Shares getShares() {
		return this.shares;
	}

	public void setShares(com.myteam.loanproduct.Shares shares) {
		this.shares = shares;
	}

	public com.myteam.loanproduct.SocialInsurance getSocialInsurance() {
		return this.socialInsurance;
	}

	public void setSocialInsurance(
			com.myteam.loanproduct.SocialInsurance socialInsurance) {
		this.socialInsurance = socialInsurance;
	}

	public com.myteam.loanproduct.HousingFund getHousingFund() {
		return this.housingFund;
	}

	public void setHousingFund(com.myteam.loanproduct.HousingFund housingFund) {
		this.housingFund = housingFund;
	}

	public java.lang.String getPaidMethod() {
		return this.paidMethod;
	}

	public void setPaidMethod(java.lang.String paidMethod) {
		this.paidMethod = paidMethod;
	}

	public Employment(java.lang.String status,
			com.myteam.loanproduct.Company company, java.lang.String position,
			java.lang.Integer monthlySalary, java.lang.String paidMethod,
			java.lang.Integer duration, com.myteam.loanproduct.Shares shares,
			com.myteam.loanproduct.SocialInsurance socialInsurance,
			com.myteam.loanproduct.HousingFund housingFund) {
		this.status = status;
		this.company = company;
		this.position = position;
		this.monthlySalary = monthlySalary;
		this.paidMethod = paidMethod;
		this.duration = duration;
		this.shares = shares;
		this.socialInsurance = socialInsurance;
		this.housingFund = housingFund;
	}

}