package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HouseCertificate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("产权人数")
	private java.lang.Integer ownerCount;
	@org.kie.api.definition.type.Label("用途")
	private java.lang.String usage;
	@org.kie.api.definition.type.Label("登记时间")
	private java.util.Date registrationDate;

	@org.kie.api.definition.type.Label(value = "\u5750\u843D")
	private com.myteam.loanproduct.District district;

	public HouseCertificate() {
	}

	public java.lang.Integer getOwnerCount() {
		return this.ownerCount;
	}

	public void setOwnerCount(java.lang.Integer ownerCount) {
		this.ownerCount = ownerCount;
	}

	public java.lang.String getUsage() {
		return this.usage;
	}

	public void setUsage(java.lang.String usage) {
		this.usage = usage;
	}

	public java.util.Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(java.util.Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	public com.myteam.loanproduct.District getDistrict() {
		return this.district;
	}

	public void setDistrict(com.myteam.loanproduct.District district) {
		this.district = district;
	}

	public HouseCertificate(java.lang.Integer ownerCount,
			java.lang.String usage, java.util.Date registrationDate,
			com.myteam.loanproduct.District district) {
		this.ownerCount = ownerCount;
		this.usage = usage;
		this.registrationDate = registrationDate;
		this.district = district;
	}

}