package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Identity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("姓名")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("生日")
	private java.util.Date birthday;
	@org.kie.api.definition.type.Label("性别")
	private Integer gender;
	@org.kie.api.definition.type.Label("身份证号")
	private java.lang.String number;
	@org.kie.api.definition.type.Label("年龄")
	private java.lang.Integer age;

	@org.kie.api.definition.type.Description("申请地与户籍所在地一致时为本地人")
	@org.kie.api.definition.type.Label("是否本地人")
	private java.lang.Boolean isLocal;

	@org.kie.api.definition.type.Label("地区")
	private com.myteam.loanproduct.District district;

	public Identity() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(java.util.Date birthday) {
		this.birthday = birthday;
	}

	public java.lang.String getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.String number) {
		this.number = number;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Boolean getIsLocal() {
		return this.isLocal;
	}

	public void setIsLocal(java.lang.Boolean isLocal) {
		this.isLocal = isLocal;
	}

	public com.myteam.loanproduct.District getDistrict() {
		return this.district;
	}

	public void setDistrict(com.myteam.loanproduct.District district) {
		this.district = district;
	}

	public java.lang.Integer getGender() {
		return this.gender;
	}

	public void setGender(java.lang.Integer gender) {
		this.gender = gender;
	}

	public Identity(java.lang.String name, java.util.Date birthday,
			java.lang.Integer gender, java.lang.String number,
			java.lang.Integer age, java.lang.Boolean isLocal,
			com.myteam.loanproduct.District district) {
		this.name = name;
		this.birthday = birthday;
		this.gender = gender;
		this.number = number;
		this.age = age;
		this.isLocal = isLocal;
		this.district = district;
	}

}