package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Industry implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ID")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "\u7EA7\u522B")
	private java.lang.String level;
	@org.kie.api.definition.type.Label(value = "\u95E8\u7C7B")
	private java.lang.String section;
	@org.kie.api.definition.type.Label(value = "\u5927\u7C7B")
	private java.lang.String division;
	@org.kie.api.definition.type.Label(value = "\u4E2D\u7C7B")
	private java.lang.String group;
	@org.kie.api.definition.type.Label(value = "\u5C0F\u7C7B")
	private java.lang.String klass;
	@org.kie.api.definition.type.Label(value = "\u540D\u79F0")
	private java.lang.String name;

	public Industry() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getLevel() {
		return this.level;
	}

	public void setLevel(java.lang.String level) {
		this.level = level;
	}

	public java.lang.String getSection() {
		return this.section;
	}

	public void setSection(java.lang.String section) {
		this.section = section;
	}

	public java.lang.String getDivision() {
		return this.division;
	}

	public void setDivision(java.lang.String division) {
		this.division = division;
	}

	public java.lang.String getGroup() {
		return this.group;
	}

	public void setGroup(java.lang.String group) {
		this.group = group;
	}

	public java.lang.String getKlass() {
		return this.klass;
	}

	public void setKlass(java.lang.String klass) {
		this.klass = klass;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Industry(java.lang.String id, java.lang.String level,
			java.lang.String section, java.lang.String division,
			java.lang.String group, java.lang.String klass,
			java.lang.String name) {
		this.id = id;
		this.level = level;
		this.section = section;
		this.division = division;
		this.group = group;
		this.klass = klass;
		this.name = name;
	}

}