package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InsurancePremium implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "\u7F34\u8D39\u671F\u95F4")
	private java.lang.Integer term;
	@org.kie.api.definition.type.Description(value = "\u5E74\u7F34\u3001\u534A\u5E74\u7F34\u3001\u5B63\u5EA6\u7F34\u3001\u6708\u7F34")
	@org.kie.api.definition.type.Label(value = "\u4EA4\u4ED8\u65B9\u5F0F")
	private java.lang.String frequency;
	@org.kie.api.definition.type.Label(value = "\u6BCF\u671F\u91D1\u989D")
	private java.lang.Integer amount;
	@org.kie.api.definition.type.Label(value = "\u9996\u6B21\u7F34\u7EB3\u65F6\u95F4")
	private java.util.Date beginDate;

	public InsurancePremium() {
	}

	public java.lang.Integer getTerm() {
		return this.term;
	}

	public void setTerm(java.lang.Integer term) {
		this.term = term;
	}

	public java.lang.String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(java.lang.String frequency) {
		this.frequency = frequency;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public java.util.Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(java.util.Date beginDate) {
		this.beginDate = beginDate;
	}

	public InsurancePremium(java.lang.Integer term, java.lang.String frequency,
			java.lang.Integer amount, java.util.Date beginDate) {
		this.term = term;
		this.frequency = frequency;
		this.amount = amount;
		this.beginDate = beginDate;
	}

}