package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LatePayments implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public LatePayments() {
    }




}