package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LifeInsurance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("保险人")
	private Company insurer;
	@org.kie.api.definition.type.Label("险种")
	private java.lang.String category;
	@org.kie.api.definition.type.Label("保险金额")
	private Float insuredAmount;
	@org.kie.api.definition.type.Label("保费")
	private com.myteam.loanproduct.InsurancePremium premium;

	public LifeInsurance() {
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public com.myteam.loanproduct.InsurancePremium getPremium() {
		return this.premium;
	}

	public void setPremium(com.myteam.loanproduct.InsurancePremium premium) {
		this.premium = premium;
	}

	public com.myteam.loanproduct.Company getInsurer() {
		return this.insurer;
	}

	public void setInsurer(com.myteam.loanproduct.Company insurer) {
		this.insurer = insurer;
	}

	public java.lang.Float getInsuredAmount() {
		return this.insuredAmount;
	}

	public void setInsuredAmount(java.lang.Float insuredAmount) {
		this.insuredAmount = insuredAmount;
	}

	public LifeInsurance(com.myteam.loanproduct.Company insurer,
			java.lang.String category, java.lang.Float insuredAmount,
			com.myteam.loanproduct.InsurancePremium premium) {
		this.insurer = insurer;
		this.category = category;
		this.insuredAmount = insuredAmount;
		this.premium = premium;
	}

}