package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("贷款金额")
	private java.lang.Integer amount;
	@org.kie.api.definition.type.Label("还款要求")
	private com.myteam.loanproduct.Repayment repayment;
	@org.kie.api.definition.type.Label("贷款申请人")
	private com.myteam.loanproduct.Applicant applicant;

	@org.kie.api.definition.type.Label(value = "\u7533\u8BF7\u5730\u533A")
	private com.myteam.loanproduct.District district;

	@org.kie.api.definition.type.Label(value = "\u53EF\u9009\u4EA7\u54C1\u5217\u8868")
	private java.util.List<java.lang.Integer> availableProductIds;

	public LoanApplication() {
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public com.myteam.loanproduct.Repayment getRepayment() {
		return this.repayment;
	}

	public void setRepayment(com.myteam.loanproduct.Repayment repayment) {
		this.repayment = repayment;
	}

	public com.myteam.loanproduct.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(com.myteam.loanproduct.Applicant applicant) {
		this.applicant = applicant;
	}

	public com.myteam.loanproduct.District getDistrict() {
		return this.district;
	}

	public void setDistrict(com.myteam.loanproduct.District district) {
		this.district = district;
	}

	public java.util.List<java.lang.Integer> getAvailableProductIds() {
		return this.availableProductIds;
	}

	public void setAvailableProductIds(
			java.util.List<java.lang.Integer> availableProductIds) {
		this.availableProductIds = availableProductIds;
	}

	public LoanApplication(java.lang.Integer amount,
			com.myteam.loanproduct.Repayment repayment,
			com.myteam.loanproduct.Applicant applicant,
			com.myteam.loanproduct.District district,
			java.util.List<java.lang.Integer> availableProductIds) {
		this.amount = amount;
		this.repayment = repayment;
		this.applicant = applicant;
		this.district = district;
		this.availableProductIds = availableProductIds;
	}

}