package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("总金额")
	private java.lang.Integer amount;
	@org.kie.api.definition.type.Label("支付时间")
	private java.util.Date payDate;

	public Order() {
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public java.util.Date getPayDate() {
		return this.payDate;
	}

	public void setPayDate(java.util.Date payDate) {
		this.payDate = payDate;
	}

	public Order(java.lang.Integer amount, java.util.Date payDate) {
		this.amount = amount;
		this.payDate = payDate;
	}

}