package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("贷款产品")
public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myteam.loanproduct.Company company;
	@org.kie.api.definition.type.Label(value = "\u4EA7\u54C1\u540D\u79F0")
	private java.lang.String name;

	public Product() {
	}

	public com.myteam.loanproduct.Company getCompany() {
		return this.company;
	}

	public void setCompany(com.myteam.loanproduct.Company company) {
		this.company = company;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Product(com.myteam.loanproduct.Company company, java.lang.String name) {
		this.company = company;
		this.name = name;
	}

}