package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("还款信息")
public class Repayment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("还款方式")
	private java.lang.String method;
	@org.kie.api.definition.type.Label("还款期（月）")
	private java.lang.Integer term;
	@org.kie.api.definition.type.Label("首次还款时间")
	private java.util.Date beginDate;
	@org.kie.api.definition.type.Label("每期还款额")
	private java.lang.Integer installment;

	@org.kie.api.definition.type.Label("利率")
	private java.lang.Float interestRate;

	@org.kie.api.definition.type.Label(value = "\u8D37\u6B3E\u91D1\u989D")
	private java.lang.Integer amount;

	public Repayment() {
	}

	public java.lang.String getMethod() {
		return this.method;
	}

	public void setMethod(java.lang.String method) {
		this.method = method;
	}

	public java.lang.Integer getTerm() {
		return this.term;
	}

	public void setTerm(java.lang.Integer term) {
		this.term = term;
	}

	public java.util.Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(java.util.Date beginDate) {
		this.beginDate = beginDate;
	}

	public java.lang.Integer getInstallment() {
		return this.installment;
	}

	public void setInstallment(java.lang.Integer installment) {
		this.installment = installment;
	}

	public java.lang.Float getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(java.lang.Float interestRate) {
		this.interestRate = interestRate;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public Repayment(java.lang.String method, java.lang.Integer term,
			java.util.Date beginDate, java.lang.Integer installment,
			java.lang.Float interestRate, java.lang.Integer amount) {
		this.method = method;
		this.term = term;
		this.beginDate = beginDate;
		this.installment = installment;
		this.interestRate = interestRate;
		this.amount = amount;
	}

}