package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Sales implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "\u5E74\u9500\u552E\u989D")
	private java.lang.Integer annualAmount;
	@org.kie.api.definition.type.Label(value = "\u6708\u9500\u552E\u989D")
	private java.lang.Integer monthlyAmount;

	public Sales() {
	}

	public java.lang.Integer getAnnualAmount() {
		return this.annualAmount;
	}

	public void setAnnualAmount(java.lang.Integer annualAmount) {
		this.annualAmount = annualAmount;
	}

	public java.lang.Integer getMonthlyAmount() {
		return this.monthlyAmount;
	}

	public void setMonthlyAmount(java.lang.Integer monthlyAmount) {
		this.monthlyAmount = monthlyAmount;
	}

	public Sales(java.lang.Integer annualAmount, java.lang.Integer monthlyAmount) {
		this.annualAmount = annualAmount;
		this.monthlyAmount = monthlyAmount;
	}

}