package com.myteam.loanproduct;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SocialInsurance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "\u57FA\u6570")
	private java.lang.Integer base;
	@org.kie.api.definition.type.Label(value = "\u8FDE\u7EED\u7F34\u7EB3\u6708\u6570")
	private java.lang.Integer continuousPaymentPeriod;

	public SocialInsurance() {
	}

	public java.lang.Integer getBase() {
		return this.base;
	}

	public void setBase(java.lang.Integer base) {
		this.base = base;
	}

	public java.lang.Integer getContinuousPaymentPeriod() {
		return this.continuousPaymentPeriod;
	}

	public void setContinuousPaymentPeriod(
			java.lang.Integer continuousPaymentPeriod) {
		this.continuousPaymentPeriod = continuousPaymentPeriod;
	}

	public SocialInsurance(java.lang.Integer base,
			java.lang.Integer continuousPaymentPeriod) {
		this.base = base;
		this.continuousPaymentPeriod = continuousPaymentPeriod;
	}

}